dist: trusty
sudo: true

language: node_js
node_js:
  - "8"

install:
  - cd common/loopringjs & npm install && cd ../..
  - npm install


script:
  - npm run build
  
cache:
  directories:
    - node_modules
