remote_theme: dong77/minimal
description: Loopring.js is a javascript library. It enables developers to quickly develop an Ethereum wallet, interact with Loopring protocol and develop a decentralized exchange. loopring.js is used in project loopr and project circular
